name: proiect-licenta-grinfo-main

services:
  db:
    container_name: proiect-licenta-grinfo-main
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: local_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  db_data:
    external: true
    name: grinfo_db_data
